// Auto-generated by pgk_gui.py — DO NOT EDIT
#ifndef MISSION_STATE_H
#define MISSION_STATE_H
namespace MissionState {
    static const double launch_long   = 88.36;
    static const double launch_lat    = 22.57;
    static const double launch_height = 10.0;
    static const double impact_long   = 88.41;
    static const double impact_lat    = 22.58;
    static const double impact_height = 0.0;
    static const char*  detonation    = "Proximity";
    static const char*  command       = "CALCULATE";
}
#endif
