import tkinter as tk
from tkinter import ttk, messagebox, filedialog
import math, os, sys, subprocess, shutil, threading, json
from datetime import datetime

# --- Military Theme Colors ---
BG_COLOR        = "#1C1C1C"
FRAME_BG        = "#2E2E2E"
TEXT_COLOR      = "#E0E0E0"
ACCENT_COLOR    = "#FFB000"
TERMINAL_GREEN  = "#00FF00"
BTN_BG          = "#333333"
BTN_ACTIVE      = "#FFB000"
ERROR_COLOR     = "#FF4444"
CONTRAST_BG     = "#FFD700"
CONTRAST_FG     = "#000000"
SAVE_COLOR      = "#005577"
LOAD_COLOR      = "#557700"
AUTOSAVE_COLOR  = "#00AA55"

HERE         = os.path.dirname(os.path.abspath(__file__))
CPP_SRC      = os.path.join(HERE, "ballistics.cpp")
CPP_EXE      = os.path.join(HERE, "ballistics.exe" if sys.platform == "win32" else "ballistics")
STATE_H      = os.path.join(HERE, "mission_state.h")
MISSIONS_DIR = os.path.join(HERE, "missions")
AUTOSAVE_FILE = os.path.join(MISSIONS_DIR, "current_mission.json")


# =====================================================================
#  C++ BRIDGE
# =====================================================================
class CppBridge:
    def __init__(self):
        self._compiled = False

    def ensure_compiled(self):
        if self._compiled and os.path.exists(CPP_EXE):
            return
        compiler = None
        for c in ("g++", "clang++", "c++"):
            if shutil.which(c):
                compiler = c
                break
        if not compiler:
            raise RuntimeError("No C++ compiler found. Install g++ / MinGW.")
        if not os.path.exists(CPP_SRC):
            raise RuntimeError(f"Missing source: {CPP_SRC}")
        r = subprocess.run(
            [compiler, "-O2", "-std=c++17", CPP_SRC, "-o", CPP_EXE],
            capture_output=True, text=True
        )
        if r.returncode != 0:
            raise RuntimeError(f"C++ compile failed:\n{r.stderr}")
        self._compiled = True

    def write_state_header(self, data: dict, command: str):
        def fmt(v):
            try:
                return str(float(v))
            except (ValueError, TypeError):
                return "0.0"
        lines = [
            "// Auto-generated by pgk_gui.py — DO NOT EDIT",
            "#ifndef MISSION_STATE_H",
            "#define MISSION_STATE_H",
            "namespace MissionState {",
            f"    static const double launch_long   = {fmt(data.get('launch_long', 0))};",
            f"    static const double launch_lat    = {fmt(data.get('launch_lat', 0))};",
            f"    static const double launch_height = {fmt(data.get('launch_height', 0))};",
            f"    static const double impact_long   = {fmt(data.get('impact_long', 0))};",
            f"    static const double impact_lat    = {fmt(data.get('impact_lat', 0))};",
            f"    static const double impact_height = {fmt(data.get('impact_height', 0))};",
            f"    static const char*  detonation    = \"{data.get('detonation_type','Impact')}\";",
            f"    static const char*  command       = \"{command}\";",
            "}",
            "#endif",
            ""
        ]
        try:
            with open(STATE_H, "w", encoding="utf-8") as f:
                f.write("\n".join(lines))
        except OSError:
            pass

    def run(self, data: dict, command: str = "CALCULATE") -> dict:
        self.ensure_compiled()
        self.write_state_header(data, command)
        payload_lines = [f"{k}={v}" for k, v in data.items()]
        payload_lines.append(f"command={command}")
        payload = "\n".join(payload_lines) + "\n"
        r = subprocess.run([CPP_EXE], input=payload,
                           capture_output=True, text=True, timeout=10)
        if r.returncode != 0:
            raise RuntimeError(f"C++ runtime error: {r.stderr}")
        out = {}
        for ln in r.stdout.strip().splitlines():
            if "=" in ln:
                k, v = ln.split("=", 1)
                out[k.strip()] = v.strip()
        return out


# =====================================================================
#  MISSION SAVE / LOAD (JSON)
# =====================================================================
class MissionStore:
    SCHEMA_VERSION = "1.0"

    @staticmethod
    def ensure_missions_dir():
        os.makedirs(MISSIONS_DIR, exist_ok=True)

    @staticmethod
    def to_dict(app, last_command: str = "CALCULATE") -> dict:
        return {
            "version": MissionStore.SCHEMA_VERSION,
            "saved_at": datetime.now().isoformat(timespec="seconds"),
            "last_command": last_command,
            "mission_name": os.path.splitext(os.path.basename(
                getattr(app, "_current_mission_path", "current_mission")))[0],
            "inputs": {
                "launch_long":   app.launch_long.get().strip(),
                "launch_lat":    app.launch_lat.get().strip(),
                "launch_height": app.launch_height.get().strip(),
                "impact_long":   app.impact_long.get().strip(),
                "impact_lat":    app.impact_lat.get().strip(),
                "impact_height": app.impact_height.get().strip(),
            },
            "detonation": {
                "type": app.detonation_combo.get(),
                "timing_label": app.detonation_timing_label.cget("text"),
            },
            "last_outputs": {
                "time_to_impact":     app.time_to_impact_var.get(),
                "time_to_detonation": app.time_at_detonation_var.get(),
                "progress":           int(app.progress_bar["value"]),
                "mono_code":          app.mono_code_var.get(),
            },
        }

    @staticmethod
    def from_dict(app, data: dict):
        inputs = data.get("inputs", {})
        app.launch_long.set(str(inputs.get("launch_long", "")))
        app.launch_lat.set(str(inputs.get("launch_lat", "")))
        app.launch_height.set(str(inputs.get("launch_height", "")))
        app.impact_long.set(str(inputs.get("impact_long", "")))
        app.impact_lat.set(str(inputs.get("impact_lat", "")))
        app.impact_height.set(str(inputs.get("impact_height", "")))

        det = data.get("detonation", {})
        det_type = det.get("type", "Impact")
        if det_type in app.detonation_options:
            app.detonation_combo.set(det_type)
        timing = det.get("timing_label")
        if timing:
            app.detonation_timing_label.config(text=timing)

        outputs = data.get("last_outputs", {})
        if outputs:
            app.time_to_impact_var.set(str(outputs.get("time_to_impact", "---")))
            app.time_at_detonation_var.set(str(outputs.get("time_to_detonation", "---")))
            try:
                app.progress_bar["value"] = float(outputs.get("progress", 0))
                app.progress_text.set(f"{int(outputs.get('progress', 0))}%")
            except (ValueError, TypeError):
                pass
            app.mono_code_var.set(str(outputs.get("mono_code", "")))


# =====================================================================
#  GUI
# =====================================================================
class PGKControlPanel:
    def __init__(self, root):
        self.root = root
        self.root.title("PGK SYSTEM - 155MM ARTILLERY CONTROL")
        self.root.geometry("1050x760")
        self.root.configure(bg=BG_COLOR, padx=25, pady=25)

        self.bridge = CppBridge()
        # Active auto-save target (default = current_mission.json)
        self._current_mission_path = AUTOSAVE_FILE
        MissionStore.ensure_missions_dir()

        self.setup_styles()
        self.init_variables()
        self.create_ui_elements()
        self._bind_shortcuts()

        threading.Thread(target=self._boot_compile, daemon=True).start()

    def _bind_shortcuts(self):
        self.root.bind("<Control-s>", lambda e: self.save_mission_as())
        self.root.bind("<Control-o>", lambda e: self.load_mission())

    def _boot_compile(self):
        try:
            self.bridge.ensure_compiled()
            self.root.after(0, lambda: self.mono_code_var.set("C++ ENGINE READY"))
        except Exception as e:
            self.root.after(0, lambda: self.mono_code_var.set("ENGINE ERROR"))
            self.root.after(0, lambda: messagebox.showerror("C++ Error", str(e)))

    def setup_styles(self):
        style = ttk.Style()
        style.theme_use("clam")
        style.configure("Military.Horizontal.TProgressbar",
                        troughcolor="#111", background=ACCENT_COLOR,
                        bordercolor="#555", lightcolor=ACCENT_COLOR, darkcolor=ACCENT_COLOR)
        style.configure("TCombobox",
                        fieldbackground=CONTRAST_BG, background=BTN_BG,
                        foreground=CONTRAST_FG, arrowcolor=CONTRAST_FG,
                        font=("Courier New", 11, "bold"))
        style.map('TCombobox',
                  fieldbackground=[('readonly', CONTRAST_BG)],
                  foreground=[('readonly', CONTRAST_FG)])

    def init_variables(self):
        self.launch_long    = tk.StringVar()
        self.launch_lat     = tk.StringVar()
        self.launch_height  = tk.StringVar()
        self.impact_long    = tk.StringVar()
        self.impact_lat     = tk.StringVar()
        self.impact_height  = tk.StringVar()

        self.mono_code_var          = tk.StringVar(value="AWAITING ENGINE...")
        self.time_to_impact_var     = tk.StringVar(value="---")
        self.time_at_detonation_var = tk.StringVar(value="---")
        self.progress_text          = tk.StringVar(value="0%")
        self.status_var             = tk.StringVar(value="STATUS: IDLE")
        self.autosave_var           = tk.StringVar(value="AUTOSAVE: current_mission.json")

    def create_ui_elements(self):
        tk.Label(self.root, text="** PGK GROUND CONTROL SYSTEM **",
                 bg=BG_COLOR, fg=ACCENT_COLOR,
                 font=("Courier New", 18, "bold")).pack(pady=(0, 20))
        self.create_launch_impact_section()
        self.create_detonation_section()
        self.create_buttons_section()
        self.create_output_section()

        # Status row (bottom)
        status_row = tk.Frame(self.root, bg=BG_COLOR)
        status_row.pack(fill="x", pady=(10, 0))
        tk.Label(status_row, textvariable=self.status_var, bg=BG_COLOR,
                 fg=TERMINAL_GREEN, font=("Courier New", 10, "bold")).pack(side="left")
        tk.Label(status_row, textvariable=self.autosave_var, bg=BG_COLOR,
                 fg=AUTOSAVE_COLOR, font=("Courier New", 10, "bold")).pack(side="right")

    def create_launch_impact_section(self):
        top_frame = tk.Frame(self.root, bg=BG_COLOR)
        top_frame.pack(fill="x", pady=10)

        launch_frame = tk.LabelFrame(top_frame, text=" LAUNCH DATA ",
                                     font=("Courier New", 11, "bold"),
                                     bg=FRAME_BG, fg=ACCENT_COLOR, bd=3,
                                     relief="ridge", padx=15, pady=15)
        launch_frame.pack(side="left", expand=True, fill="both", padx=(0, 15))
        self.create_input_field(launch_frame, "LONG:",   self.launch_long,   0)
        self.create_input_field(launch_frame, "LAT:",    self.launch_lat,    1)
        self.create_input_field(launch_frame, "HEIGHT:", self.launch_height, 2)

        impact_frame = tk.LabelFrame(top_frame, text=" IMPACT DATA ",
                                     font=("Courier New", 11, "bold"),
                                     bg=FRAME_BG, fg=ACCENT_COLOR, bd=3,
                                     relief="ridge", padx=15, pady=15)
        impact_frame.pack(side="right", expand=True, fill="both", padx=(15, 0))
        self.create_input_field(impact_frame, "LONG:",   self.impact_long,   0)
        self.create_input_field(impact_frame, "LAT:",    self.impact_lat,    1)
        self.create_input_field(impact_frame, "HEIGHT:", self.impact_height, 2)

    def create_input_field(self, parent, label_text, variable, row):
        tk.Label(parent, text=label_text, bg=FRAME_BG, fg=TEXT_COLOR,
                 font=("Courier New", 11, "bold")).grid(row=row, column=0,
                                                        sticky="w", pady=8)
        entry = tk.Entry(parent, textvariable=variable, width=18, bg="#111",
                         fg=TERMINAL_GREEN, insertbackground=TERMINAL_GREEN,
                         font=("Courier New", 12), bd=3, relief="sunken")
        entry.grid(row=row, column=1, padx=10, ipady=4)
        # Return → calculate (which now auto-saves)
        entry.bind("<Return>", lambda e: self.calculate_ballistics())

    def create_detonation_section(self):
        detonation_frame = tk.LabelFrame(self.root, text=" DETONATION & MISSION STATUS ",
                                         font=("Courier New", 11, "bold"),
                                         bg=FRAME_BG, fg=ACCENT_COLOR, bd=3,
                                         relief="ridge", padx=15, pady=15)
        detonation_frame.pack(fill="x", pady=15)

        row0 = tk.Frame(detonation_frame, bg=FRAME_BG)
        row0.pack(fill="x", pady=5)
        tk.Label(row0, text="DETONATION TYPE:", bg=FRAME_BG, fg=TEXT_COLOR,
                 font=("Courier New", 11, "bold")).pack(side="left")

        self.detonation_options = ["Impact", "Time", "Proximity", "IED", "Manual Override"]
        self.detonation_combo = ttk.Combobox(row0, values=self.detonation_options,
                                             state="readonly", width=18,
                                             font=("Courier New", 11, "bold"))
        self.detonation_combo.pack(side="left", padx=15, ipady=3)
        self.detonation_combo.set("Impact")
        self.detonation_combo.bind("<<ComboboxSelected>>", self.on_detonation_select)

        tk.Label(row0, text="DETONATION TIMING:", bg=FRAME_BG, fg=TEXT_COLOR,
                 font=("Courier New", 11, "bold")).pack(side="left", padx=(30, 5))
        self.detonation_timing_label = tk.Label(row0, text="T+Impact", bg="#111",
                                                fg=TERMINAL_GREEN,
                                                font=("Courier New", 12, "bold"),
                                                width=18, bd=3, relief="sunken")
        self.detonation_timing_label.pack(side="left", ipady=4)

        row1 = tk.Frame(detonation_frame, bg=FRAME_BG)
        row1.pack(fill="x", pady=15)
        tk.Label(row1, text="MISSION PROGRESS:", bg=FRAME_BG, fg=TEXT_COLOR,
                 font=("Courier New", 11, "bold")).pack(side="left")
        self.progress_bar = ttk.Progressbar(row1, orient="horizontal", length=400,
                                            mode="determinate",
                                            style="Military.Horizontal.TProgressbar")
        self.progress_bar.pack(side="left", padx=15)
        tk.Label(row1, textvariable=self.progress_text, bg=FRAME_BG,
                 fg=ACCENT_COLOR, font=("Courier New", 12, "bold")).pack(side="left")

    def create_buttons_section(self):
        button_frame = tk.Frame(self.root, bg=BG_COLOR, pady=10)
        button_frame.pack()

        cast_frame = tk.LabelFrame(button_frame, text=" CASTING & CALCULATION ",
                                   font=("Courier New", 11, "bold"),
                                   bg=FRAME_BG, fg=ACCENT_COLOR, bd=3,
                                   relief="ridge", padx=15, pady=15)
        cast_frame.pack(side="left", padx=8)

        self.btn_calc = tk.Button(cast_frame, text="CALCULATE", width=10,
                                  command=self.calculate_ballistics,
                                  bg="#004400", fg=TERMINAL_GREEN,
                                  activebackground="#00FF00", activeforeground="#000",
                                  font=("Courier New", 11, "bold"),
                                  bd=4, relief="raised")
        self.btn_calc.grid(row=0, column=0, padx=6, ipady=5)

        self.btn_mono = tk.Button(cast_frame, text="MONO CAST", width=10,
                                  command=self.run_mono_cast,
                                  bg=BTN_BG, fg=ACCENT_COLOR,
                                  activebackground=BTN_ACTIVE, activeforeground="#000",
                                  font=("Courier New", 11, "bold"),
                                  bd=4, relief="raised")
        self.btn_mono.grid(row=0, column=1, padx=6, ipady=5)

        self.btn_mass = tk.Button(cast_frame, text="MASS CAST", width=10,
                                  command=self.run_mass,
                                  bg=BTN_BG, fg=ACCENT_COLOR,
                                  activebackground=BTN_ACTIVE, activeforeground="#000",
                                  font=("Courier New", 11, "bold"),
                                  bd=4, relief="raised")
        self.btn_mass.grid(row=0, column=2, padx=6, ipady=5)

        mission_frame = tk.LabelFrame(button_frame, text=" MISSION FILE ",
                                      font=("Courier New", 11, "bold"),
                                      bg=FRAME_BG, fg="#66CCFF", bd=3,
                                      relief="ridge", padx=15, pady=15)
        mission_frame.pack(side="left", padx=8)

        self.btn_save = tk.Button(mission_frame, text="💾 SAVE AS", width=10,
                                  command=self.save_mission_as,
                                  bg=SAVE_COLOR, fg="#FFFFFF",
                                  activebackground="#66CCFF", activeforeground="#000",
                                  font=("Courier New", 11, "bold"),
                                  bd=4, relief="raised")
        self.btn_save.grid(row=0, column=0, padx=6, ipady=5)

        self.btn_load = tk.Button(mission_frame, text="📂 LOAD", width=10,
                                  command=self.load_mission,
                                  bg=LOAD_COLOR, fg="#FFFFFF",
                                  activebackground="#AADD55", activeforeground="#000",
                                  font=("Courier New", 11, "bold"),
                                  bd=4, relief="raised")
        self.btn_load.grid(row=0, column=1, padx=6, ipady=5)

        instant_frame = tk.LabelFrame(button_frame, text=" EMERGENCY ",
                                      font=("Courier New", 11, "bold"),
                                      bg=FRAME_BG, fg=ERROR_COLOR, bd=3,
                                      relief="ridge", padx=15, pady=15)
        instant_frame.pack(side="right", padx=8)
        self.btn_instant = tk.Button(instant_frame, text="INSTANT DETONATION", width=19,
                                     command=self.run_instant,
                                     bg="#550000", fg=ERROR_COLOR,
                                     activebackground=ERROR_COLOR, activeforeground="#FFF",
                                     font=("Courier New", 11, "bold"),
                                     bd=4, relief="raised")
        self.btn_instant.pack(ipady=5)

    def create_output_section(self):
        output_frame = tk.Frame(self.root, bg=BG_COLOR, pady=10)
        output_frame.pack(fill="x")
        output_frame.columnconfigure(0, weight=1)
        output_frame.columnconfigure(1, weight=1)
        output_frame.columnconfigure(2, weight=1)

        mono_frame = tk.LabelFrame(output_frame, text=" MONOCAST CODE ",
                                   font=("Courier New", 10, "bold"),
                                   bg=FRAME_BG, fg=ACCENT_COLOR, bd=3,
                                   relief="ridge", padx=10, pady=10)
        mono_frame.grid(row=0, column=0, sticky="nsew", padx=(0, 10))
        self.mono_entry = tk.Entry(mono_frame, textvariable=self.mono_code_var,
                                   width=22, bg="#111", fg=TERMINAL_GREEN,
                                   insertbackground=TERMINAL_GREEN,
                                   font=("Courier New", 12), bd=3, relief="sunken")
        self.mono_entry.pack(padx=5, pady=5, fill="x", ipady=4)
        self.mono_entry.bind("<Return>", lambda e: self.run_mono_cast())

        tti_frame = tk.LabelFrame(output_frame, text=" TIME TO IMPACT ",
                                  font=("Courier New", 10, "bold"),
                                  bg=FRAME_BG, fg=ACCENT_COLOR, bd=3,
                                  relief="ridge", padx=10, pady=10)
        tti_frame.grid(row=0, column=1, sticky="nsew", padx=10)
        tk.Entry(tti_frame, textvariable=self.time_to_impact_var, width=22,
                 state="readonly", bg=CONTRAST_BG, fg=CONTRAST_FG,
                 font=("Courier New", 12, "bold"), bd=4,
                 relief="sunken").pack(padx=5, pady=5, fill="x", ipady=4)

        tad_frame = tk.LabelFrame(output_frame, text=" TIME TO DETONATION ",
                                  font=("Courier New", 10, "bold"),
                                  bg=FRAME_BG, fg=ACCENT_COLOR, bd=3,
                                  relief="ridge", padx=10, pady=10)
        tad_frame.grid(row=0, column=2, sticky="nsew", padx=(10, 0))
        tk.Entry(tad_frame, textvariable=self.time_at_detonation_var, width=22,
                 state="readonly", bg=CONTRAST_BG, fg=CONTRAST_FG,
                 font=("Courier New", 12, "bold"), bd=4,
                 relief="sunken").pack(padx=5, pady=5, fill="x", ipady=4)

    # ---------------- BRIDGE ----------------
    def _gather_inputs(self):
        return {
            "launch_long":   self.launch_long.get().strip()  or "0",
            "launch_lat":    self.launch_lat.get().strip()   or "0",
            "launch_height": self.launch_height.get().strip()or "0",
            "impact_long":   self.impact_long.get().strip()  or "0",
            "impact_lat":    self.impact_lat.get().strip()   or "0",
            "impact_height": self.impact_height.get().strip()or "0",
            "detonation_type": self.detonation_combo.get(),
        }

    def _call_cpp(self, command):
        data = self._gather_inputs()
        for k in ("launch_long","launch_lat","launch_height",
                  "impact_long","impact_lat","impact_height"):
            try:
                float(data[k])
            except ValueError:
                self._show_error(f"Invalid {k}")
                return None
        try:
            return self.bridge.run(data, command)
        except Exception as e:
            self._show_error(str(e))
            return None

    def _show_error(self, msg):
        self.time_to_impact_var.set("INPUT ERR")
        self.time_at_detonation_var.set("INPUT ERR")
        self.progress_text.set("0%")
        self.mono_code_var.set("INVALID COORDINATES")
        self.status_var.set(f"STATUS: ERROR — {msg}")
        self.progress_bar['value'] = 0

    def _apply_output(self, out):
        if not out: return
        self.time_to_impact_var.set(f"{out.get('time_to_impact','0')} s")
        self.time_at_detonation_var.set(f"{out.get('time_to_detonation','0')} s")
        self.progress_bar['value'] = float(out.get('progress', 0))
        self.progress_text.set(f"{out.get('progress','0')}%")
        self.mono_code_var.set(out.get('mono_code', ''))
        self.status_var.set(f"STATUS: {out.get('status','OK')}")

    # ---------------- AUTO-SAVE ----------------
    def _autosave(self, last_command: str = "CALCULATE"):
        """Silently write current mission state to the active JSON file."""
        try:
            MissionStore.ensure_missions_dir()
            payload = MissionStore.to_dict(self, last_command=last_command)
            payload["mission_name"] = os.path.splitext(
                os.path.basename(self._current_mission_path))[0]
            with open(self._current_mission_path, "w", encoding="utf-8") as f:
                json.dump(payload, f, indent=2)
            ts = datetime.now().strftime("%H:%M:%S")
            self.autosave_var.set(
                f"AUTOSAVE ✓ {os.path.basename(self._current_mission_path)} @ {ts}"
            )
        except Exception as e:
            self.autosave_var.set(f"AUTOSAVE FAILED: {e}")

    # ---------------- BUTTON HANDLERS ----------------
    def calculate_ballistics(self):
        out = self._call_cpp("CALCULATE")
        self._apply_output(out)
        if out:                              # only autosave on success
            self._autosave(last_command="CALCULATE")

    def on_detonation_select(self, event):
        sel = self.detonation_combo.get()
        self.detonation_timing_label.config(text={
            "Time": "T+0.00s (Delay)",
            "Proximity": "T+Proximity",
            "Impact": "T+Impact",
            "IED": "Signal Based",
            "Manual Override": "Awaiting Input",
        }.get(sel, "T+Impact"))
        self.calculate_ballistics()

    def run_mono_cast(self):
        out = self._call_cpp("MONO_CAST")
        self._apply_output(out)
        if out:
            self._autosave(last_command="MONO_CAST")

    def run_mass(self):
        out = self._call_cpp("MASS_CAST")
        self._apply_output(out)
        if out:
            self._autosave(last_command="MASS_CAST")

    def run_instant(self):
        out = self._call_cpp("INSTANT_DETONATION")
        self._apply_output(out)
        if out:
            self._autosave(last_command="INSTANT_DETONATION")

    # ================ SAVE AS / LOAD ================
    def save_mission_as(self):
        """Choose a new filename; from then on auto-save writes to it."""
        MissionStore.ensure_missions_dir()
        initial = os.path.join(
            MISSIONS_DIR,
            f"mission_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
        )
        path = filedialog.asksaveasfilename(
            title="Save Mission As",
            initialdir=MISSIONS_DIR,
            initialfile=os.path.basename(initial),
            defaultextension=".json",
            filetypes=[("JSON Mission", "*.json"), ("All Files", "*.*")]
        )
        if not path:
            return
        self._current_mission_path = path
        self._autosave(last_command="SAVE_AS")
        self.status_var.set(f"STATUS: SWITCHED TO ← {os.path.basename(path)}")

    def load_mission(self):
        """Load JSON; the loaded file becomes the new auto-save target."""
        MissionStore.ensure_missions_dir()
        path = filedialog.askopenfilename(
            title="Load Mission",
            initialdir=MISSIONS_DIR,
            filetypes=[("JSON Mission", "*.json"), ("All Files", "*.*")]
        )
        if not path:
            return

        try:
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)

            if not isinstance(data, dict) or "inputs" not in data:
                raise ValueError("File is not a valid PGK mission (missing 'inputs').")

            version = data.get("version", "?")
            MissionStore.from_dict(self, data)
            self._current_mission_path = path   # switch autosave target

            # Recompute C++ outputs from loaded inputs (and autosave refresh)
            out = self._call_cpp("CALCULATE")
            self._apply_output(out)
            if out:
                self._autosave(last_command="LOAD")

            self.status_var.set(
                f"STATUS: LOADED ← {os.path.basename(path)}  (schema v{version})"
            )
        except json.JSONDecodeError as e:
            messagebox.showerror("Load Failed", f"Invalid JSON:\n{e}")
            self.status_var.set("STATUS: LOAD FAILED (bad JSON)")
        except Exception as e:
            messagebox.showerror("Load Failed", f"Could not load mission:\n{e}")
            self.status_var.set("STATUS: LOAD FAILED")


if __name__ == "__main__":
    root = tk.Tk()
    app = PGKControlPanel(root)
    root.mainloop()